project:
  type: website

website:
  title: "Population Dynamics in Latin America"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - href: pop_growth.qmd
        text: Urbanization vs. Population Growth
      - href: pop_decline.qmd
        text: Death Rate vs. Birth Rate
      - href: conclusion.qmd
        text: Conclusion
      - about.qmd

format:
  html:
    theme: 
      - journal  
    css: styles.css
    toc: true
  pdf:
    toc: true
    number-sections: true


