---
title: "Fertility rates among adolescents"
---

Which countries have a disproportionately high adolescent fertility rate?

This page explores the patterns of fertility rate (overall, and just among adolescents) in four Latin American countries: Colombia, Brazil, Argentina, and Mexico.

## Results 
```{python}
#| echo: false
#| eval: true

import pandas as pd
import sqlite3
import matplotlib.pyplot as plt
import seaborn as sns

# Connect to sql
conn = sqlite3.connect('data/wdi_data.db')  

# SQL query
query = """
SELECT 
    country,
    fertility_rate,
    (adolescent_fertility_rate/1000) AS ado_fertility_rate
FROM wdi_data
WHERE fertility_rate IS NOT NULL AND adolescent_fertility_rate IS NOT NULL
ORDER BY fertility_rate DESC;
"""
df = pd.read_sql_query(query, conn)

display(pd.read_sql(query, conn))

```

```{python}
#| label: natural_rate_barplot
#| echo: false
#| eval: true
#| fig-cap: "Fertility rate plot"



# Plot
plt.figure(figsize=(12, 6))
sns.scatterplot(
    data=df, 
    x='fertility_rate', y='ado_fertility_rate', 
    hue='country',
    s = 300
)

plt.grid(True)
plt.xlim(1.4, 2.2)
plt.title('Adolescent vs. overall fertility rate')
plt.ylabel('Births per female aged 15-19')
plt.xlabel('Births per female')
plt.tight_layout()
plt.show()

```

## Interpretation 
Though it's hard to tell with only four points of comparison, we can see Colombia is somewhat of an outlier in this analysis. Its adolescent fertility rate is disproportionately high compared to its *overall* fertility rate, indicating that Colombians aged 15-19 give birth more than would be expected compared to the rest of the Colombian population.

This trend is confirmed in other studies, which attributes the high adolescent fertility, in part, to Colombia's "illegality of abortion"[@daniels2015tackling].